minimumReleaseAge: 1440

registries:
  default: https://registry.npmjs.org/

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@openapitools/openapi-generator-cli'
  - '@sentry/cli'
  - esbuild
  - spawn-sync
  - vue-demi

allowBuilds:
  '@nestjs/core': true
  '@openapitools/openapi-generator-cli': true
  '@sentry/cli': true
  esbuild: true
  spawn-sync: true
  vue-demi: true
