quarkus.application.name=chainlink-api
# separating root-path and non-application-root-path
# allows for making the api public but keeping /q stuff private
quarkus.http.root-path=/api
quarkus.http.non-application-root-path=/q
# Keep in Sync with Enum "AppLanguage"
quarkus.locales=de-CH,fr-CH,it-CH,en-US
quarkus.default-locale=de-CH

### api
%dev.app.deployment.environment=LOCAL
%test.app.deployment.environment=UNIT_TEST
%prod.app.deployment.environment=${CLINK_API_DEPLOYMENT_ENVIRONMENT}
app.deployment.public-url=${CLINK_API_DEPLOYMENT_PUBLIC_URL}
%test.app.deployment.public-url=https://local-chainlink.localhost:4443/
app.deployment.version=${APP_VERSION:${quarkus.application.version}}
app.deployment.app-project=chainlink
app.deployment.app-module=api
app.deployment.instance=${CLINK_API_DEPLOYMENT_INSTANCE:${HOSTNAME}}
%dev.app.deployment.instance=dev-${USERNAME:${USER:${USER_FALLBACK}}}
%test.app.deployment.instance=unit-test-${USERNAME:${USER:${USER_FALLBACK:QUARKUSTEST}}}

%dev.quarkus.hibernate-orm.log.sql=false
%test.quarkus.hibernate-orm.log.sql=false
%dev.quarkus.hibernate-orm.scripts.generation=create
%dev.quarkus.hibernate-orm.scripts.generation.create-target=src/main/resources/db/test-migration/V1.0.0__test-init.sql
#%test.quarkus.log.min-level=TRACE
#%test.quarkus.hibernate-orm.log.bind-parameters=true

### HTTP
%dev.quarkus.http.host=0.0.0.0
%test.quarkus.http.host=localhost
%dev.quarkus.http.ssl.certificate.files=../developer-local-settings/config/certs/multi-domain.pem
%dev.quarkus.http.ssl.certificate.key-files=../developer-local-settings/config/certs/multi-domain.key
%dev.quarkus.http.insecure-requests=disabled
quarkus.http.header."Strict-Transport-Security".value=max-age=31536000; includeSubDomains; preload
quarkus.http.header."X-Content-Type-Options".value=nosniff
quarkus.http.limits.max-body-size=20M

# DEV UI
%dev.quarkus.dev-ui.hosts=local-chainlink.localhost,localhost
%dev.quarkus.dev-ui.cors.enabled=false

# DATABASE
quarkus.datasource.db-kind=sqlite
quarkus.datasource.jdbc.url=jdbc:sqlite:../developer-local-settings/chainlink.db?foreign_keys=on&busy_timeout=30000
%test.quarkus.datasource.jdbc.url=jdbc:sqlite:chainlink-test.db?foreign_keys=on&busy_timeout=30000


# FLYWAY
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration
%test.quarkus.flyway.clean-disabled=false

# JACKSON
quarkus.rest.jackson.optimization.enable-reflection-free-serializers=false



### SECURITY

## OIDC (Google) - active for dev and prod
# Redirect URI for Google Console: {public-url}api/q/authorized
quarkus.oidc.auth-server-url=https://accounts.google.com
quarkus.oidc.client-id=838049690608-usqf9c42iau16bneim1ckcj1q4v74bou.apps.googleusercontent.com
quarkus.oidc.credentials.secret=${CL_OIDC_CLIENT_SECRET}
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.scopes=openid,profile,email
quarkus.oidc.token.principal-claim=email
%dev.quarkus.oidc.authentication.cookie-domain=dev-chainlink.markushofstetter.com
%prod.quarkus.oidc.authentication.cookie-domain=chainlink.markushofstetter.com


# Disable OIDC for test (use form auth instead)
%test.quarkus.oidc.enabled=false

## Form-based auth - active for test only
#quarkus.http.auth.form.enabled=false
#%test.quarkus.http.auth.form.enabled=true
#%test.quarkus.http.auth.form.login-page=
#%test.quarkus.http.auth.form.landing-page=
#%test.quarkus.http.auth.form.error-page=
#%test.quarkus.http.auth.form.http-only-cookie=true
#%test.quarkus.http.auth.session.encryption-key=chainlink-form-auth-encryption-key
# todo remove this later
quarkus.http.auth.form.enabled=true
quarkus.http.auth.form.login-page=
quarkus.http.auth.form.landing-page=
quarkus.http.auth.form.error-page=
quarkus.http.auth.form.http-only-cookie=true
quarkus.http.auth.form.cookie-name=chainlink-credential
quarkus.http.auth.session.encryption-key=${CL_FORM_LOGIN_COOKIE_SECRET}
%test.quarkus.http.auth.session.encryption-key=${CL_FORM_LOGIN_COOKIE_SECRET:someSecretKey}


## Proxy
quarkus.http.proxy.proxy-address-forwarding=true
quarkus.http.proxy.allow-x-forwarded=true
quarkus.http.proxy.enable-forwarded-host=true



quarkus.log.category."io.quarkus.oidc.client.runtime.OidcClientRecorder".level=TRACE
quarkus.log.category."io.quarkus.oidc.client.runtime.OidcClientRecorder".min-level=TRACE
quarkus.log.category."io.quarkus.oidc.client.runtime.OidcClientImpl".level=TRACE
quarkus.log.category."io.quarkus.oidc.client.runtime.OidcClientImpl".min-level=TRACE

# Disable rate limiting in test
%test.quarkus.fault-tolerance."org.chainlink.api.auth.AuthResource/register".rate-limit.value=1000
