ALTER TABLE Bookmark ADD COLUMN click_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE Bookmark ADD COLUMN last_clicked_at TIMESTAMP;

ALTER TABLE Bookmark_AUD ADD COLUMN click_count INTEGER;
ALTER TABLE Bookmark_AUD ADD COLUMN last_clicked_at TIMESTAMP;
