create table Bookmark (click_count integer not null, deleted_at timestamp, last_clicked_at timestamp, timestampErstellt timestamp not null, timestampMutiert timestamp not null, version bigint not null, collection_id varchar(36) not null, folder_id varchar(36), id varchar(36) not null, url varchar(2000) not null, description varchar(5000), title varchar(255) not null, userErstellt varchar(255) not null, userMutiert varchar(255) not null, primary key (id));
create table Bookmark_Tag (bookmark_id varchar(36) not null, tag_id varchar(36) not null, primary key (bookmark_id, tag_id));
create table Collection (timestampErstellt timestamp not null, timestampMutiert timestamp not null, version bigint not null, id varchar(36) not null, owner_id varchar(36) not null, name varchar(255) not null, userErstellt varchar(255) not null, userMutiert varchar(255) not null, primary key (id));
create table CollectionAccess (isDefault boolean not null, timestampErstellt timestamp not null, timestampMutiert timestamp not null, version bigint not null, role varchar(30) not null check ((role in ('OWNER','MEMBER'))), collection_id varchar(36) not null, id varchar(36) not null, user_id varchar(36) not null, userErstellt varchar(255) not null, userMutiert varchar(255) not null, primary key (id));
create table Folder (color varchar(7), deleted_at timestamp, timestampErstellt timestamp not null, timestampMutiert timestamp not null, version bigint not null, collection_id varchar(36) not null, id varchar(36) not null, parent_id varchar(36), name varchar(255) not null, userErstellt varchar(255) not null, userMutiert varchar(255) not null, primary key (id));
create table REVINFO (REV integer, REVTSTMP bigint, primary key (REV));
create table Tag (color varchar(7) not null, timestampErstellt timestamp not null, timestampMutiert timestamp not null, version bigint not null, collection_id varchar(36) not null, id varchar(36) not null, name varchar(255) not null, userErstellt varchar(255) not null, userMutiert varchar(255) not null, primary key (id));
create table User (aktiv boolean not null, lastUsedSessionTimestamp timestamp, timestampErstellt timestamp not null, timestampLastManuallyActivated timestamp, timestampMutiert timestamp not null, version bigint not null, authProvider varchar(30) check ((authProvider in ('OIDC','FORM'))), id varchar(36) not null, password varchar(60), fachRollen varchar(2000), email varchar(255) not null, keycloakId varchar(255), lastUsedIp varchar(255), lastUsedSessionId varchar(255), nachname varchar(255) not null, oidcIssuer varchar(255), titel varchar(255), userErstellt varchar(255) not null, userMutiert varchar(255) not null, vorname varchar(255) not null, primary key (id));
create table User_AUD (REV integer not null, REVTYPE tinyint, aktiv boolean, lastUsedSessionTimestamp timestamp, timestampErstellt timestamp, timestampLastManuallyActivated timestamp, timestampMutiert timestamp, authProvider varchar(30) check ((authProvider in ('OIDC','FORM'))), id varchar(36) not null, password varchar(60), fachRollen varchar(2000), email varchar(255), keycloakId varchar(255), lastUsedIp varchar(255), lastUsedSessionId varchar(255), nachname varchar(255), oidcIssuer varchar(255), titel varchar(255), userErstellt varchar(255), userMutiert varchar(255), vorname varchar(255), primary key (REV, id));
create table UserPermission (timestampErstellt timestamp not null, timestampMutiert timestamp not null, version bigint not null, id varchar(36) not null, user_id varchar(36) not null, permission varchar(255) not null check ((permission in ('SUPPORT','SYSTEM_ADMIN','BOOKMARK_READ','BOOKMARK_WRITE'))), userErstellt varchar(255) not null, userMutiert varchar(255) not null, primary key (id));
create table UserPermission_AUD (REV integer not null, REVTYPE tinyint, timestampErstellt timestamp, timestampMutiert timestamp, id varchar(36) not null, user_id varchar(36), permission varchar(255) check ((permission in ('SUPPORT','SYSTEM_ADMIN','BOOKMARK_READ','BOOKMARK_WRITE'))), userErstellt varchar(255), userMutiert varchar(255), primary key (REV, id));
create index ix_bookmark_collection_id on Bookmark (collection_id, id);
create index ix_bookmark_folder_id on Bookmark (folder_id, id);
create index ix_bookmark_tag_bookmark_id on Bookmark_Tag (bookmark_id, tag_id);
create index ix_bookmark_tag_tag_id on Bookmark_Tag (tag_id, bookmark_id);
create index ix_collection_owner_id on Collection (owner_id, id);
create index ix_collectionaccess_user_id on CollectionAccess (user_id, id);
create index ix_collectionaccess_collection_id on CollectionAccess (collection_id, id);
create index ix_collectionaccess_user_default on CollectionAccess (user_id, isDefault);
create index ix_folder_collection_id on Folder (collection_id, id);
create index ix_folder_parent_id on Folder (parent_id, id);
create index ix_tag_collection_id on Tag (collection_id, id);
create index ix_user_id on User (id, version);
create index ix_user_email on User (email, id);
create index ix_user_keycloakId on User (keycloakId, id);
create index ix_userpermission_user_id on UserPermission (user_id, id);
