import type { Command, Option } from 'commander'

export const COMPLETION_SHELLS = ['bash', 'zsh', 'fish'] as const

export type CompletionShell = (typeof COMPLETION_SHELLS)[number]

interface SubcommandInfo {
  name: string
  description: string
}

interface OptionInfo {
  /** Both spellings of the flag, e.g. ['-f', '--format']. */
  flags: string[]
  description: string
  takesValue: boolean
  /** Completable values for options declared with .choices(). */
  choices?: string[]
}

interface CompletionNode {
  /** Subcommand path from the program root, e.g. ['bookmarks', 'add']. */
  path: string[]
  subcommands: SubcommandInfo[]
  options: OptionInfo[]
  /** Completable values of positional arguments declared with .choices(). */
  argChoices: string[]
}

function toOptionInfo(option: Option): OptionInfo {
  const flags: string[] = []
  if (option.short) flags.push(option.short)
  if (option.long) flags.push(option.long)
  return {
    flags,
    description: option.description,
    takesValue: option.required || option.optional,
    choices: option.argChoices,
  }
}

/**
 * Flattens the commander command tree into one node per command path, so the
 * shell scripts below are always generated from the real program definition —
 * a new command or flag shows up in completions without touching this file.
 */
export function collectNodes(root: Command): CompletionNode[] {
  const nodes: CompletionNode[] = []
  const visit = (cmd: Command, path: string[]): void => {
    nodes.push({
      path,
      subcommands: cmd.commands.map((sub) => ({ name: sub.name(), description: sub.description() })),
      options: cmd.options.filter((option) => !option.hidden).map(toOptionInfo),
      argChoices: cmd.registeredArguments.flatMap((argument) => argument.argChoices ?? []),
    })
    for (const sub of cmd.commands) visit(sub, [...path, sub.name()])
  }
  visit(root, [])
  return nodes
}

/** The words to offer once the user has typed the node's command path. */
function wordsFor(node: CompletionNode, globalOptions: OptionInfo[]): string[] {
  const words = [
    ...node.subcommands.map((sub) => sub.name),
    // Commander registers an implicit `help` subcommand on every parent.
    ...(node.subcommands.length > 0 ? ['help'] : []),
    ...node.argChoices,
    ...node.options.flatMap((option) => option.flags),
    // Global options parse after subcommand names too (commander default).
    ...globalOptions.flatMap((option) => option.flags),
    '-h',
    '--help',
  ]
  return [...new Set(words)]
}

/** Nodes ordered deepest-first so prefix matching hits the most specific one. */
function orderedNodes(nodes: CompletionNode[]): { deep: CompletionNode[]; root: CompletionNode } {
  const root = nodes.find((node) => node.path.length === 0)
  if (!root) throw new Error('command tree has no root node')
  const deep = nodes.filter((node) => node.path.length > 0).sort((a, b) => b.path.length - a.path.length)
  return { deep, root }
}

/** Flags that consume the following word, e.g. `--collection Work`. */
function valueFlags(nodes: CompletionNode[]): string[] {
  const flags = nodes.flatMap((node) => node.options.filter((o) => o.takesValue).flatMap((o) => o.flags))
  return [...new Set(flags)]
}

/** Options with a fixed value set, keyed by their `-f|--format` alternation. */
function choiceArms(nodes: CompletionNode[]): { pattern: string; values: string[] }[] {
  const byPattern = new Map<string, Set<string>>()
  for (const node of nodes) {
    for (const option of node.options) {
      if (!option.choices || option.choices.length === 0) continue
      const pattern = option.flags.join('|')
      const values = byPattern.get(pattern) ?? new Set()
      for (const value of option.choices) values.add(value)
      byPattern.set(pattern, values)
    }
  }
  return [...byPattern.entries()].map(([pattern, values]) => ({ pattern, values: [...values] }))
}

export function completionScript(shell: CompletionShell, root: Command): string {
  const nodes = collectNodes(root)
  switch (shell) {
    case 'bash':
      return bashScript(nodes)
    case 'zsh':
      return zshScript(nodes)
    case 'fish':
      return fishScript(nodes)
  }
}

function bashScript(nodes: CompletionNode[]): string {
  const { deep, root } = orderedNodes(nodes)
  const skipPattern = valueFlags(nodes).join('|')
  const prevArms = choiceArms(nodes)
    .map(({ pattern, values }) => `    ${pattern}) COMPREPLY=($(compgen -W "${values.join(' ')}" -- "$cur")); return ;;`)
    .join('\n')
  const contextArms = deep
    .map((node) => `    "${node.path.join(' ')}"*) words="${wordsFor(node, root.options).join(' ')}" ;;`)
    .join('\n')
  return `# bash completion for linkweave — generated by 'linkweave completion bash'
_linkweave() {
  local cur prev words
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD - 1]}"

  case "$prev" in
${prevArms}
  esac

  # The command context is every previous word that is not a flag or a flag's
  # value, e.g. 'bookmarks add' in 'linkweave -s URL bookmarks add --title T'.
  local -a cmdwords=()
  local i w skip=0
  for ((i = 1; i < COMP_CWORD; i++)); do
    w="\${COMP_WORDS[i]}"
    if ((skip)); then skip=0; continue; fi
    case "$w" in
      ${skipPattern}) skip=1 ;;
      -*) ;;
      *) cmdwords+=("$w") ;;
    esac
  done

  case "\${cmdwords[*]}" in
${contextArms}
    *) words="${wordsFor(root, []).join(' ')}" ;;
  esac
  COMPREPLY=($(compgen -W "$words" -- "$cur"))
}
complete -F _linkweave linkweave
`
}

function zshScript(nodes: CompletionNode[]): string {
  const { deep, root } = orderedNodes(nodes)
  const skipPattern = valueFlags(nodes).join('|')
  const prevArms = choiceArms(nodes)
    .map(({ pattern, values }) => `    ${pattern}) compadd -- ${values.join(' ')}; return ;;`)
    .join('\n')
  const contextArms = deep
    .map((node) => `    "${node.path.join(' ')}"*) completions=(${wordsFor(node, root.options).join(' ')}) ;;`)
    .join('\n')
  return `# zsh completion for linkweave — generated by 'linkweave completion zsh'
# Load after compinit, e.g. in ~/.zshrc: eval "$(linkweave completion zsh)"
_linkweave() {
  local -a cmdwords completions
  local w prev skip=0
  (( CURRENT > 2 )) && prev="\${words[CURRENT - 1]}"

  case "$prev" in
${prevArms}
  esac

  for w in "\${(@)words[2,CURRENT - 1]}"; do
    if ((skip)); then skip=0; continue; fi
    case "$w" in
      ${skipPattern}) skip=1 ;;
      -*) ;;
      *) cmdwords+=("$w") ;;
    esac
  done

  case "\${(j: :)cmdwords}" in
${contextArms}
    *) completions=(${wordsFor(root, []).join(' ')}) ;;
  esac
  compadd -- "\${completions[@]}"
}
compdef _linkweave linkweave
`
}

function fishEscape(text: string): string {
  return text.replace(/[\\"$]/g, '\\$&')
}

function fishScript(nodes: CompletionNode[]): string {
  const { deep, root } = orderedNodes(nodes)
  const lines = [
    '# fish completion for linkweave — generated by \'linkweave completion fish\'',
    'complete -c linkweave -f',
  ]
  const optionLine = (option: OptionInfo, condition?: string): string => {
    const parts = ['complete -c linkweave']
    if (condition) parts.push(`-n "${condition}"`)
    for (const flag of option.flags) {
      parts.push(flag.startsWith('--') ? `-l ${flag.slice(2)}` : `-s ${flag.slice(1)}`)
    }
    if (option.choices && option.choices.length > 0) parts.push(`-x -a "${option.choices.join(' ')}"`)
    else if (option.takesValue) parts.push('-r')
    if (option.description) parts.push(`-d "${fishEscape(option.description)}"`)
    return parts.join(' ')
  }
  for (const option of root.options) lines.push(optionLine(option))
  for (const sub of root.subcommands) {
    lines.push(
      `complete -c linkweave -n __fish_use_subcommand -a ${sub.name} -d "${fishEscape(sub.description)}"`,
    )
  }
  for (const node of deep) {
    // Require every path segment, not just the last: 'bookmarks list' and
    // 'collections list' share their final segment.
    const seen = node.path.map((segment) => `__fish_seen_subcommand_from ${segment}`).join('; and ')
    for (const sub of node.subcommands) {
      const notSeen = `not __fish_seen_subcommand_from ${[...node.subcommands.map((s) => s.name), 'help'].join(' ')}`
      lines.push(
        `complete -c linkweave -n "${seen}; and ${notSeen}" -a ${sub.name} -d "${fishEscape(sub.description)}"`,
      )
    }
    for (const option of node.options) lines.push(optionLine(option, seen))
    if (node.argChoices.length > 0) {
      lines.push(`complete -c linkweave -n "${seen}" -a "${node.argChoices.join(' ')}"`)
    }
  }
  return lines.join('\n') + '\n'
}
